-- Generated by Matugen

local base00 = "{{colors.background.default.hex}}"
local base01 = "{{colors.surface_container_lowest.default.hex}}"
local base02 = "{{colors.surface_container_low.default.hex}}"
local base03 = "{{colors.outline_variant.default.hex}}"
local base04 = "{{colors.on_surface_variant.default.hex}}"
local base05 = "{{colors.on_surface.default.hex}}"
local base06 = "{{colors.inverse_on_surface.default.hex}}"
local base07 = "{{colors.surface_bright.default.hex}}"

local base08 = "{{colors.tertiary.default.hex | lighten: -5}}"
local base09 = "{{colors.tertiary.default.hex}}"
local base0A = "{{colors.secondary.default.hex}}"
local base0B = "{{colors.primary.default.hex}}"
local base0C = "{{colors.tertiary_container.default.hex}}"
local base0D = "{{colors.primary_container.default.hex}}"
local base0E = "{{colors.secondary_container.default.hex}}"
local base0F = "{{colors.secondary.default.hex | lighten: -10}}"

return {
  "RRethy/nvim-base16",
  lazy = false,
  priority = 1000,
  config = function()
    require("base16-colorscheme").setup({
      base00 = base00,
      base01 = base01,
      base02 = base02,
      base03 = base03,
      base04 = base04,
      base05 = base05,
      base06 = base06,
      base07 = base07,
      base08 = base08,
      base09 = base09,
      base0A = base0A,
      base0B = base0B,
      base0C = base0C,
      base0D = base0D,
      base0E = base0E,
      base0F = base0F,
    })

    -- We first theme base16, but we also need to fix some other colors that don't
    -- contrast well by default

    -- Helper function to set multiple highlight groups at once
    local function set_hl_mutliple(groups, value)
      for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
      end
    end

    -- Make selected text stand out more
    vim.api.nvim_set_hl(0, "Visual", {
      bg = base0D,
      fg = base06, -- light foreground for contrast on primary_container bg
    })

    -- Make "string" text contrast better
    set_hl_mutliple({ "String", "TSString" }, {
      fg = base08,
    })

    -- Grey out comments
    set_hl_mutliple({ "TSComment", "Comment" }, {
      fg = base03,
      italic = true,
    })

    -- Color in other highlight groups as you see fit!

    set_hl_mutliple({ "TSMethod", "Method" }, {
      fg = base09,
    })

    set_hl_mutliple({ "TSFunction", "Function" }, {
      fg = base0A,
    })

    set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
      fg = base0E,
    })
  end,
}
