- name: Installed required libs for brave
  become: true
  apt:
    name: [ "curl", "apt-transport-https" ]

- name: Install Brave keyring
  become: true
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg

- name: Brave browser PPA settings
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

- name: Brave browser apt installation
  become: true
  apt:
    update_cache: yes
    name: brave-browser
