- name: Create themes dir
  shell: mkdir -p $HOME/.themes $HOME/.config/gtk-3.0 $HOME/.config/gtk-4.0 $HOME/.icons

- name: Download Catppuccin Mocha theme
  get_url:
    url: https://github.com/catppuccin/gtk/releases/download/v0.7.1/Catppuccin-Mocha-Standard-Sky-Dark.zip
    dest: $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark.zip

- name: Unzip theme
  shell: unzip $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark.zip -d $HOME/.themes

- name: Link dirs
  shell: ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-3.0/gtk.css $HOME/.config/gtk-3.0/gtk.css && ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-3.0/gtk-dark.css $HOME/.config/gtk-3.0/gtk-dark.css && ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-3.0/assets $HOME/.config/gtk-3.0/assets && ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-4.0/gtk.css $HOME/.config/gtk-4.0/gtk.css && ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-4.0/gtk-dark.css $HOME/.config/gtk-4.0/gtk-dark.css && ln -sf $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark/gtk-4.0/assets $HOME/.config/gtk-4.0/assets

- name: Clean up
  shell: rm $HOME/.themes/Catppuccin-Mocha-Standard-Sky-Dark.zip

- name: Install papirus icons
  shell: wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR="$HOME/.icons" sh
