- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: b

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    dest: /tmp/install

- name: Install Homebrew
  shell: bash /tmp/install < /dev/null
  when: not b.stat.exists

- name: Reset the Homebrew Library repo
  git: 
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no

- name: Install Neovim
  homebrew:
    name: neovim
    state: latest
