- hosts: localhost
  tasks:
    #- include_tasks: tasks/core-tools.yml
    #- include_tasks: tasks/snap.yml
    #- include_tasks: tasks/zsh.yml
    #- include_tasks: tasks/brave.yml
    - include_tasks: tasks/i3.yml
    #- include_tasks: tasks/homebrew.yml
    #    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/gtk.yml
