cursor #a9b1d6
cursor_text_color #9aa5ce

foreground            #a9b1d6
background            #16161e
selection_foreground  #1a1b26
selection_background  #bb9af7
url_color             #7dcfff

color0   #1a1b26
color1   #ff709d
color2   #7dff8c
color3   #fff670
color4   #5ebbf2
color5   #074d76
color6   #7dcfff
color7   #eff9ff
color8   #99a1a5
color9   #ff9dbc
color10  #a4ffae
color11  #fff9a4
color12  #90d6ff
color13  #a4ddff
color14  #c4e9ff
color15  #f8fcff
